/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projpharma;

/**
 *
 * @author mende
 */
public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbCPF = new javax.swing.JLabel();
        TxtCodCli = new javax.swing.JTextField();
        TxtNomCli = new javax.swing.JTextField();
        jblNome = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        CmbSexo = new javax.swing.JComboBox<>();
        jlbTel = new javax.swing.JLabel();
        TxtTelCli = new javax.swing.JTextField();
        jlbCel = new javax.swing.JLabel();
        TxtCelCli = new javax.swing.JTextField();
        jlbCep = new javax.swing.JLabel();
        TxtCepCli = new javax.swing.JTextField();
        jlbCidade = new javax.swing.JLabel();
        TxtCidCli = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        TxtRuaCli = new javax.swing.JTextField();
        jlbNum = new javax.swing.JLabel();
        TxtNumCli = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TxtCidCli1 = new javax.swing.JTextField();
        OsseoOpt = new javax.swing.JRadioButton();
        CardioOpt = new javax.swing.JRadioButton();
        PulmonarOpt = new javax.swing.JRadioButton();
        RenalOpt = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        FumanteSOpt = new javax.swing.JRadioButton();
        FumanteNOpt = new javax.swing.JRadioButton();
        AlcolNOpt = new javax.swing.JRadioButton();
        GravidaNOpt = new javax.swing.JRadioButton();
        GravidaSOpt = new javax.swing.JRadioButton();
        AlcolSOpt = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        FumanteNOpt1 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        FumanteSOpt1 = new javax.swing.JRadioButton();
        FumanteNOpt2 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        FumanteSOpt2 = new javax.swing.JRadioButton();
        BtnSalvar = new javax.swing.JButton();
        BtnAlterar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();
        BtnProximo = new javax.swing.JButton();
        BtnUltimo = new javax.swing.JButton();
        BtnAnterior = new javax.swing.JButton();
        BtnPrimeiro = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbCPF.setText("CPF:");

        TxtCodCli.setToolTipText("Exemplo:123.456.789/00");
        TxtCodCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCodCliActionPerformed(evt);
            }
        });

        TxtNomCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomCliActionPerformed(evt);
            }
        });

        jblNome.setText("Nome:");

        jLabel3.setText("Sexo:");

        CmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"-Selecione-", "Masculino", "Feminino"}));
        CmbSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbSexoActionPerformed(evt);
            }
        });

        jlbTel.setText("Telefone:");

        TxtTelCli.setToolTipText("Exemplo:123.456.789/00");
        TxtTelCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTelCliActionPerformed(evt);
            }
        });

        jlbCel.setText("Celular:");

        TxtCelCli.setToolTipText("Exemplo:123.456.789/00");
        TxtCelCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCelCliActionPerformed(evt);
            }
        });

        jlbCep.setText("CEP:");

        TxtCepCli.setToolTipText("Exemplo:123.456.789/00");
        TxtCepCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCepCliActionPerformed(evt);
            }
        });

        jlbCidade.setText("Cidade:");

        TxtCidCli.setToolTipText("Exemplo:123.456.789/00");
        TxtCidCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCidCliActionPerformed(evt);
            }
        });

        jLabel8.setText("Rua:");

        TxtRuaCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRuaCliActionPerformed(evt);
            }
        });

        jlbNum.setText("Num.:");

        TxtNumCli.setToolTipText("Exemplo:123.456.789/00");
        TxtNumCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNumCliActionPerformed(evt);
            }
        });

        jLabel10.setText("Cidade:");

        TxtCidCli1.setToolTipText("Exemplo:123.456.789/00");
        TxtCidCli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCidCli1ActionPerformed(evt);
            }
        });

        OsseoOpt.setText("Problema \u00D3sseo");

        CardioOpt.setText("Problema Cardio Vascular");
        CardioOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardioOptActionPerformed(evt);
            }
        });

        PulmonarOpt.setText("Problema Pulmonar");
        PulmonarOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PulmonarOptActionPerformed(evt);
            }
        });

        RenalOpt.setText("Problema Renal");
        RenalOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RenalOptActionPerformed(evt);
            }
        });

        jLabel11.setText("Fumante");

        jLabel12.setText("Alcoolatra");

        jLabel13.setText("Gr\u00E1vida");

        FumanteSOpt.setText("Sim");
        FumanteSOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FumanteSOptActionPerformed(evt);
            }
        });

        FumanteNOpt.setText("N\u00E3o");
        FumanteNOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FumanteNOptActionPerformed(evt);
            }
        });

        AlcolNOpt.setText("N\u00E3o");
        AlcolNOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlcolNOptActionPerformed(evt);
            }
        });

        GravidaNOpt.setText("N\u00E3o");
        GravidaNOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GravidaNOptActionPerformed(evt);
            }
        });

        GravidaSOpt.setText("Sim");
        GravidaSOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GravidaSOptActionPerformed(evt);
            }
        });

        AlcolSOpt.setText("Sim");
        AlcolSOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlcolSOptActionPerformed(evt);
            }
        });

        FumanteNOpt1.setText("N\u00E3o");
        FumanteNOpt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FumanteNOpt1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Portador de doen\u00E7a cr\u00F3nica?");

        FumanteSOpt1.setText("Sim");
        FumanteSOpt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FumanteSOpt1ActionPerformed(evt);
            }
        });

        FumanteNOpt2.setText("N\u00E3o");
        FumanteNOpt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FumanteNOpt2ActionPerformed(evt);
            }
        });

        jLabel15.setText("Al\u00E9rgico?");

        FumanteSOpt2.setText("Sim");
        FumanteSOpt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FumanteSOpt2ActionPerformed(evt);
            }
        });

        BtnSalvar.setText("Salvar");
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        BtnAlterar.setText("Alterar");
        BtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlterarActionPerformed(evt);
            }
        });

        BtnExcluir.setText("Excluir");
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        BtnProximo.setText(">");
        BtnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProximoActionPerformed(evt);
            }
        });

        BtnUltimo.setText(">>");
        BtnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUltimoActionPerformed(evt);
            }
        });

        BtnAnterior.setText("<");
        BtnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnteriorActionPerformed(evt);
            }
        });

        BtnPrimeiro.setText("<<");
        BtnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrimeiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addComponent(jSeparator2)
            .addComponent(jSeparator1)
            .addComponent(jSeparator4)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FumanteNOpt1)
                                    .addComponent(FumanteSOpt1)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtCidCli1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RenalOpt)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbCep, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TxtCepCli, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlbCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtCidCli, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbCel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtCelCli, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlbTel)
                                .addGap(10, 10, 10)
                                .addComponent(TxtTelCli, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbCPF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtCodCli, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtNomCli, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(TxtRuaCli, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(jlbNum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtNumCli, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PulmonarOpt)
                            .addComponent(CardioOpt)
                            .addComponent(OsseoOpt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FumanteNOpt)
                                    .addComponent(FumanteSOpt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AlcolSOpt)
                                    .addComponent(AlcolNOpt)
                                    .addComponent(FumanteSOpt2)
                                    .addComponent(FumanteNOpt2)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GravidaNOpt)
                                    .addComponent(GravidaSOpt))))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BtnSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnAlterar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnExcluir)
                                .addGap(71, 71, 71)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnAnterior)
                                .addGap(26, 26, 26)
                                .addComponent(BtnProximo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnPrimeiro)
                                .addGap(18, 18, 18)
                                .addComponent(BtnUltimo)))
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCPF)
                    .addComponent(TxtCodCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNomCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCel)
                    .addComponent(TxtCelCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTelCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbTel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCepCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCidCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbCidade)
                    .addComponent(jlbCep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtRuaCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(TxtNumCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCidCli1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OsseoOpt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CardioOpt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PulmonarOpt))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FumanteSOpt)
                            .addComponent(GravidaSOpt)
                            .addComponent(AlcolSOpt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FumanteNOpt)
                            .addComponent(AlcolNOpt)
                            .addComponent(GravidaNOpt))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RenalOpt)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FumanteSOpt1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FumanteNOpt1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FumanteSOpt2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FumanteNOpt2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnSalvar)
                            .addComponent(BtnAlterar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnExcluir))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BtnAnterior)
                                .addComponent(BtnProximo))
                            .addGap(31, 31, 31))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnPrimeiro)
                            .addComponent(BtnUltimo))))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCodCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCodCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodCliActionPerformed

    private void TxtNomCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomCliActionPerformed

    private void CmbSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbSexoActionPerformed

    private void TxtTelCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTelCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTelCliActionPerformed

    private void TxtCelCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCelCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCelCliActionPerformed

    private void TxtCepCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCepCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCepCliActionPerformed

    private void TxtCidCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCidCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCidCliActionPerformed

    private void TxtRuaCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRuaCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRuaCliActionPerformed

    private void TxtNumCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNumCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNumCliActionPerformed

    private void TxtCidCli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCidCli1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCidCli1ActionPerformed

    private void CardioOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardioOptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardioOptActionPerformed

    private void PulmonarOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PulmonarOptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PulmonarOptActionPerformed

    private void RenalOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RenalOptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RenalOptActionPerformed

    private void FumanteSOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FumanteSOptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FumanteSOptActionPerformed

    private void FumanteNOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FumanteNOptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FumanteNOptActionPerformed

    private void AlcolNOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlcolNOptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlcolNOptActionPerformed

    private void GravidaNOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GravidaNOptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GravidaNOptActionPerformed

    private void GravidaSOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GravidaSOptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GravidaSOptActionPerformed

    private void AlcolSOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlcolSOptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlcolSOptActionPerformed

    private void FumanteNOpt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FumanteNOpt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FumanteNOpt1ActionPerformed

    private void FumanteSOpt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FumanteSOpt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FumanteSOpt1ActionPerformed

    private void FumanteNOpt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FumanteNOpt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FumanteNOpt2ActionPerformed

    private void FumanteSOpt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FumanteSOpt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FumanteSOpt2ActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void BtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAlterarActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void BtnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProximoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnProximoActionPerformed

    private void BtnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUltimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUltimoActionPerformed

    private void BtnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAnteriorActionPerformed

    private void BtnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrimeiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPrimeiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AlcolNOpt;
    private javax.swing.JRadioButton AlcolSOpt;
    private javax.swing.JButton BtnAlterar;
    private javax.swing.JButton BtnAnterior;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnPrimeiro;
    private javax.swing.JButton BtnProximo;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JButton BtnUltimo;
    private javax.swing.JRadioButton CardioOpt;
    private javax.swing.JComboBox<String> CmbSexo;
    private javax.swing.JRadioButton FumanteNOpt;
    private javax.swing.JRadioButton FumanteNOpt1;
    private javax.swing.JRadioButton FumanteNOpt2;
    private javax.swing.JRadioButton FumanteSOpt;
    private javax.swing.JRadioButton FumanteSOpt1;
    private javax.swing.JRadioButton FumanteSOpt2;
    private javax.swing.JRadioButton GravidaNOpt;
    private javax.swing.JRadioButton GravidaSOpt;
    private javax.swing.JRadioButton OsseoOpt;
    private javax.swing.JRadioButton PulmonarOpt;
    private javax.swing.JRadioButton RenalOpt;
    private javax.swing.JTextField TxtCelCli;
    private javax.swing.JTextField TxtCepCli;
    private javax.swing.JTextField TxtCidCli;
    private javax.swing.JTextField TxtCidCli1;
    private javax.swing.JTextField TxtCodCli;
    private javax.swing.JTextField TxtNomCli;
    private javax.swing.JTextField TxtNumCli;
    private javax.swing.JTextField TxtRuaCli;
    private javax.swing.JTextField TxtTelCli;
    private javax.swing.JLabel jlbCPF;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jblNome;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jlbTel;
    private javax.swing.JLabel jlbCel;
    private javax.swing.JLabel jlbCep;
    private javax.swing.JLabel jlbCidade;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jlbNum;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
